### ISSUE TITLE
Require Open-source LICENSE

### ISSUE THREAD

**Issue by Cle2ment** [MilkPuppy/-#1]
It is recommended that you should add an open-source LICENSE to this and each repository.
Wish you good luck, your studio as well. 😀

**Comment by Cle2ment** [comment]
If you need any help on designing your static website page for your studio, you can contact me into the program. Salute!

**Comment by BoningtonChen** [comment]
LICENSE created. PR is now closed

**Comment by Cle2ment** [comment]
LICENSE is now added and PR is greeted. 👍🏻
